### ISSUE TITLE
:us Independence Day is not set to to_weekday_if_weekend

### ISSUE THREAD

**Issue by wubwubwalrus-od** [Teamweek/holidefs#23]
Thanks for helping us to improve. Please fill the following info so we can help you help us:

- Elixir version: any
- Holidefs version: 0.3.1

### How to repeat

    {:ok, ind_day} = Date.new(2021, 7, 5)
    Holidefs.on(:us, ind_day, %Holidefs.Options{observed?: true, regions: ["us"], include_informal?: false}) # returns {:ok, []}

In region "us", July 4th holiday is not set to be observed on the nearest weekday. For example, in the code above, Independence Day falls on a Sunday but 2021-07-05 which is the Monday after does not return any holidays. In the definitions for us.yaml, Independence Day is not configured with observed: to_weekday_if_weekend(date)

### Expected behaviour

2021-07-05 should be the observed day for Independence Day according to the sources mentioned in the comments on the us.yaml file:

https://www.timeanddate.com/holidays/us/
https://publicholidays.us/2021-dates/

**Comment by kelvinst** [comment]
Nice catch, PR is welcome

**Comment by wubwubwalrus-od** [comment]
here is the PR: https://github.com/Teamweek/holidefs/pull/24

**Comment by wubwubwalrus-od** [comment]
@kelvinst bump on this ^

**Comment by kelvinst** [comment]
Solved by #24

**Comment by wubwubwalrus-od** [comment]
@kelvinst , can this change be published to hex please? ty!

**Comment by kelvinst** [comment]
I think we will do it in the near future, meanwhile you can use `{:holidefs, "~> 0.3", github: "teamweek/holidefs", branch: "master"}`, as the only change in there is this one.
